# Generated by Django 3.1 on 2022-05-20 09:03

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('youshopweship', '0005_auto_20220520_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=phone_field.models.PhoneField(help_text='Contact phone number', max_length=31),
        ),
    ]
