# Generated by Django 3.1 on 2022-05-23 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youshopweship', '0010_auto_20220520_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile',
            field=models.CharField(error_messages={'required': 'Enter a valid Phone Number'}, max_length=10, validators=[django.core.validators.RegexValidator(regex='^(0|91)?[6-9][0-9]{9}')]),
        ),
    ]
